default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL_SIZE") { 10 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  username: <%= ENV.fetch("DB_USER") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "fraud_detection_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "fraud_detection_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "fraud_detection_production" } %>